from setuptools import setup, find_packages

setup(
    name="go2-locomotion",
    version="0.1.0",
    description="Quadruped locomotion framework with RL policies and visualization tools",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.21.0",
        "gymnasium>=0.28.0",
        "stable-baselines3>=2.0.0",
        "tensorboard>=2.12.0",
        "pybullet>=3.2.5",
        "mujoco>=2.3.0",
        "matplotlib>=3.6.0",
        "plotly>=5.15.0",
        "opencv-python>=4.7.0",
        "imageio>=2.25.0",
        "imageio-ffmpeg>=0.4.8",
        "pyvista>=0.40.0",
        "vtk>=9.2.0",
        "trimesh>=3.20.0",
        "tqdm>=4.65.0",
        "wandb>=0.15.0",
        "pyyaml>=6.0",
        "scipy>=1.10.0",
        "scikit-learn>=1.2.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)

